apiVersion: batch/v1
kind: Job
metadata:
  name: iperf-client
spec:
  template:
    spec:
      restartPolicy: Never
      terminationGracePeriodSeconds: 5
      containers:
      - name: iperf
        image: networkstatic/iperf3
        args:
        - "-c"
        - "iperf-server"
        - "-t"
        - "10"
        resources:
          requests:
            cpu: 50m
            memory: 32Mi
